'use strict';
const scenes=[
 {title:'Everyone starts on the same page.',copy:'A quick stock and attendance check gives the office a clear starting point.',metrics:[['248','Full cylinders'],['12 / 14','Team checked in']],rows:[['Opening stock','Recorded'],['Empty cylinders','164 available'],['Today’s team','Ready to assign']]},
 {title:'A plan the whole team can follow.',copy:'Keep assignments and delivery updates together as the day gets moving.',metrics:[['4','Routes planned'],['68','Deliveries assigned']],rows:[['North zone · Ravi','18 deliveries'],['Market road · Anita','24 deliveries'],['East zone · Kumar','26 deliveries']]},
 {title:'Every sale. Every payment.',copy:'Record cash, UPI and credit alongside each sale, so collections stay visible.',metrics:[['₹42,600','Sales recorded'],['₹3,200','Pending collections']],rows:[['Cash received','₹21,400'],['UPI received','₹18,000'],['Customer credit','₹3,200']]},
 {title:'Know where you stand at day-end.',copy:'Compare system stock with the godown and delivery team before closing the day.',metrics:[['180','System full stock'],['180','Godown + delivery team']],rows:[['Full cylinder variance','Matched'],['Empty cylinder variance','Matched'],['Day’s sales register','Ready to review']]}
];
let currentStep=0;
function showStep(index){currentStep=index;const scene=scenes[index];document.querySelectorAll('[data-step]').forEach((b,i)=>{b.setAttribute('aria-selected',String(i===index));b.tabIndex=i===index?0:-1;});const panel=document.getElementById('journey-panel');panel.setAttribute('aria-labelledby',`step-${index}`);panel.innerHTML=`<div class="preview-label">EnergyAlly / Illustrative product preview</div><h3>${scene.title}</h3><p>${scene.copy}</p><div class="preview-metrics">${scene.metrics.map(([n,l])=>`<div><strong>${n}</strong><span>${l}</span></div>`).join('')}</div>${scene.rows.map(([l,r])=>`<div class="preview-row"><span>${l}</span><span>${r}</span></div>`).join('')}<button class="journey-next">${index===3?'Start the day again':'Next moment'} →</button>`;panel.querySelector('button').onclick=()=>showStep((index+1)%4);}
document.querySelectorAll('[data-step]').forEach(b=>{b.onclick=()=>showStep(Number(b.dataset.step));b.onkeydown=e=>{let i=Number(b.dataset.step);if(e.key==='ArrowRight'||e.key==='ArrowDown')i=(i+1)%4;else if(e.key==='ArrowLeft'||e.key==='ArrowUp')i=(i+3)%4;else if(e.key==='Home')i=0;else if(e.key==='End')i=3;else return;e.preventDefault();showStep(i);document.getElementById(`step-${i}`).focus();};});showStep(0);
const menu=document.querySelector('.menu-toggle'),links=document.querySelector('.nav-links');menu.onclick=()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));links.classList.toggle('open',open);};function closeMenu(){menu.setAttribute('aria-expanded','false');links.classList.remove('open');}links.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
const photos=['lpg','petroleum','solar','water'];function verticalPhoto(index){const photo=document.getElementById('vertical-photo');photo.src=index===0?'assets/images/energy-distribution-hero.webp':index===1?'assets/images/lpg.jpg':`assets/images/${photos[index]}.jpg`;photo.alt=`${photos[index]} industry`;document.querySelectorAll('#vtabs button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));}document.querySelectorAll('#vtabs button').forEach((b,i)=>b.addEventListener('click',()=>verticalPhoto(i)));document.querySelectorAll('[data-industry]').forEach(b=>b.onclick=()=>{document.querySelectorAll('#vtabs button')[Number(b.dataset.industry)].click();document.getElementById('verticals').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});verticalPhoto(0);
const minutes=document.getElementById('admin-minutes'),days=document.getElementById('work-days');function calculate(){document.getElementById('minute-output').textContent=`${minutes.value} minutes`;document.getElementById('time-result').textContent=Number(minutes.value)*Number(days.value)/60;}minutes.oninput=calculate;days.onchange=calculate;
document.querySelectorAll('.plan .btn').forEach(b=>b.addEventListener('click',()=>{document.getElementById('contact-notes').value=`I am interested in the ${b.closest('.plan').querySelector('h3').textContent} plan (${document.querySelector('#ptoggle button.active').textContent.toLowerCase()}).`;}));
const demo=document.getElementById('demoForm');demo.addEventListener('submit',async e=>{e.preventDefault();if(!demo.reportValidity())return;const button=demo.querySelector('[type=submit]'),status=document.getElementById('demo-status');button.disabled=true;button.textContent='Sending…';status.textContent='';const data=new FormData(demo);const payload={name:data.get('name').trim(),phone:data.get('biz').trim(),email:data.get('email').trim(),sector:document.querySelector('#vsel .active').dataset.v,notes:data.get('msg').trim(),teamSize:'',source:'energyally-website',requestedAt:new Date().toISOString()};try{await fetch('https://script.google.com/macros/s/AKfycbzE-bGp6TpHnUHdaaIe0MlZycJct5LVePIGh7rcV7EkIYm1Fl7k8sFO4E8DAhjcC3_Bbw/exec',{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload),signal:AbortSignal.timeout(15000)});status.dataset.state='sent';status.textContent='Thank you for your interest in EnergyAlly! Our team will be in touch to arrange your personalised demo.';demo.reset();}catch(error){status.dataset.state='error';status.textContent='We could not send your request. Please try again or email sales@energyally.in.';}finally{button.disabled=false;button.textContent='Submit demo request →';}});
